### ISSUE TITLE
Opcode: Ceil

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#109]
For what reason was the support of the opcode 'ceil' disabled?

It's not very convenient to use a macro to round up...

**Comment by NovaRain** [comment]
From extra.c in sslc:
> // ceil function temporarily disabled because vanilla "floor" function works incorrectly with negative values

**Comment by FakelsHub** [comment]
Why cannot use the function с++ 'floor', instead of a engine 'floor'?

**Comment by phobos2077** [comment]
> Why cannot use the function с++ 'floor', instead of a engine 'floor'?

The answer is simple - it is vanilla function and if you change it, you risk breaking some of the existing scripts. The same situation as with function to get item in NPC inactive hand :)

**Comment by FakelsHub** [comment]
Round тоже функция движка?

**Comment by FakelsHub** [comment]
> ceil function temporarily disabled because vanilla "floor"

Возвращаясь данной к функции, хотелось бы узнать каким образом движковая функция 'floor' относится к функции 'ceil' из с++ ?

`ctx.setReturn(static_cast<int>(ceil(ctx.arg(0).asFloat())));`
Вот здесь в коде используется встроенная функция ceil из языка С++, и никаким образом это не связано с выше упомянутой с движковой floor

Я у себя в компиляторе включил использование функции ceil, и не наблюдаю никаких ошибок в ее использовании.

**Comment by NovaRain** [comment]
I think the reason about vanilla "floor" is its inconsistency. The vanilla "floor" works exactly the same as "ceil" for negative value (and that also makes the ceil marco in lib.math.h return incorrect negative values). It's actually more like "trunc" in C++ instead of ordinary "floor".

While enabling the new and proper "ceil" function doesn't effect the functionality of vanilla "floor", the results would make people confused. Because in common programming languages floor&ceil should be a pair, but it's not what we got in SSL when the value is negative.

**Comment by FakelsHub** [comment]
> While enabling the new and proper "ceil" function doesn't effect the functionality of vanilla "floor", the results would make people confused.

I do not quite understand how the result of 'ceil' can confuse people? :)
Especially if vanilla 'floor' works like 'trunc', then need to add an additional(correct) function 'sfall_floor' - then there will be a correct pair of 'floor & ceil'.

**Comment by NovaRain** [comment]
OK, I've added a "floor2" function in critter_inven_obj2's fashion. ceil will be enabled in sslc and int2ssl.
