### ISSUE TITLE
Function Round

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#137]
Incorrectly rounds numbers, `round(14 * 20 / 100) = 2`
Should round to the nearest whole number.

Heh, if you write so `round(14 * 20 / 100.0) = 3` then rounds correctly.

**Comment by NovaRain** [comment]
AFAIK at least one of values have to be float, so that the game will treat the result from the division as a float. If all dividend & divisor are integer, the result will only be the integer quotient, and the remainder is discarded.

You can try to print the result in message box:
(14 * 20 / 100) = 2
(14 * 20 / 100.0) = 2.80000
