### ISSUE TITLE
unlimited copmpanion stages possible?

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#138]
or even up to say 10 or so,would be great

**Comment by NovaRain** [comment]
It's possible to increase the internal companion stage limit in the engine, but it would also increase the memory usage. So it's not too practical to make it "unlimited" if you literally mean it, or to some extremely high cap.

Another way is to script the levelup of your companions. Fallout 1.5: Resurrection uses scripting method to handle levelup of companions instead of using the standard party.txt + protos of all stages for companions, but there's a chance for glitch.

**Comment by nirran** [comment]
no not litteraly,10 would be great,ill look at that mod,thnx

**Comment by nirran** [comment]
Another way is to script the levelup of your companions. Fallout 1.5: Resurrection uses scripting method to handle levelup of companions instead of using the standard party.txt + protos of all stages for companions, but there's a chance for glitch.

is this method compatible with get_npc_level(PID_VIC) ?

**Comment by NovaRain** [comment]
No, the way FO1.5 uses for party member leveling is different. If you extract its fores.dat, you can check how it scripts the leveling up in NPC scripts.

**Comment by nirran** [comment]
boo then i cannot use my party perks with F01.5 party member method
