### ISSUE TITLE
A number of feature requests

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#14]
I've a number of requests. I'm not sure which are doable easily, or at all, or maybe something is already possible with scripting. If you'd like to have a separate issue for each one for discussion, please let me know and I'll do that.

1. A hotkey to highlight critters and transition areas (as an alternative to long option of entering combat mode, then exiting it). Could be the same or different key that is currently used to highlight items. Preferably different colors, though.

2. (From Crafty's) an option to auto reload both weapons at the end of combat

3. Runtime party control toggle. Probably a long shot, but I thought I'd ask. Reason is that controlling the party manually all the time is overly tedious, and not really worth it. But just once in a while, you really need the NPC to take cover, or shoot a specific enemy. And of course, it doesn't happen. A key allowing to toggle between these 2 modes would be perfect.

4. Display occupied/total weight (and space, when space limit is enabled) in containers. Trunk specifically, but other containers also would be great.

5. Automatically open/walk through unlocked doors.

6. Instant weapon equip/switch - to disable the annoying animation delay when searching containers.

7. In barter/steal/loot, use a key, like shift+right click to move items back and forth. (and something like ctrl-rclick could be used to move the whole stack)

8. (From Crafty's) On weapon reload in inventory screen, automatically load full magazine - skipping number dialog.

9. A hotkey to center screen on dude

**Comment by NovaRain** [comment]
About no.9, have you tried the Home key?

**Comment by burner1024** [comment]
Oh... I don't have a Home key.
I didn't know that about containers. That would be just space, then.

**Comment by phobos2077** [comment]
As NovaRain said, no.9 is available in vanilla game.
Let's split this into separate issues for each feature request, so it will be easier to manage and discuss (in case someone else will participate in discussion).

I see this is mostly convenience features. Some of that can be scripted but not trivially. For interface stuff, instead of Crafty's approach of hard-coding every feature, I would prefer to make UI scriptable. That, of course, requires more work at first, but in the end, everyone will be able to tweak UI as they desire, because everyone has an opinion on what features should be added. Hard-coding everything in will make Sfall a mess (more than it is now) in terms of configuration and source code.
It is easy to make EXE hacks when you are just making a few of them, but when you want tons of hacks, they will eventually start to conflict with each other and at that point it will be painful to maintain them.

**Comment by burner1024** [comment]
Done, I created separate ones. I understand that this is a lot of requests, and you might not have time or inclination to work on that, even if you think they're good ideas (which is not necessarily true). However, just in case you do - I'm putting them for discussion. Not harm in asking, yes?
