### ISSUE TITLE
3.8 Crash

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#281]
You need to find this part of the code, it's a naked script handler.
![2020-02-06_20-03-03](https://user-images.githubusercontent.com/21695363/73961123-0ed5e700-491d-11ea-907e-65a53df0acb1.png)

**Comment by FakelsHub** [comment]
`__declspec(naked) get_array`

It is possible that there is no error in this handler, but something is broken in the stack after it, and the EDI register does have the not correct value after popad

**Comment by NovaRain** [comment]
Thank you so much for find the cause. It confirms my earlier finding that the crash might be related to script arrays. I guess it requires to rewrite nearly all array-related code in 3.8, probably doesn't worth the effort. At least I can update the "known issues" section in the readme to mention the real cause better.

**Comment by NovaRain** [comment]
It seems the cause is the `pushad/popad` in the opcode, or specifically the push/pop of `esp` register. My amateur test today:
I saw the maximum number of registers being push/pop in vanilla opcodes are 6: `ebx`, `ecx`, `edx`, `esi`, `edi`, and `ebp`, so I replace all `pushad/popad` in ScriptArrays.hpp with new macros:
```cpp
#define pushopc __asm push ebx __asm push ecx __asm push edx __asm push edi __asm push esi __asm push ebp
#define popopc __asm pop ebp __asm pop esi __asm pop edi __asm pop edx __asm pop ecx __asm pop ebx
```
Surprisingly I didn't get the crash with the same testing scenario (using EcCo's hs_barterprice and intentionally remove a script file attached on a scenery object). Adding `push/pop eax` to the macros and nothing happens. If I added `push/pop esp`, the game just crashed right after game load.

The hook script itself seems working fine (item price modified as it should). I guess maybe it's better to replace all `pushad/popad` in 3.8's opcode handlers in *.hpp?
