### ISSUE TITLE
What does OverrideMusicDir do?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#295]
> ;Set to 1 to override the music path used by default (i.e. data\sound\music\) if not present in the cfg
;Set to 2 to overwrite all occurances of the music path

Override to what, and why?

Also, I tried to pack music into `.dat`, and it doesn't seems to work (no music played). Is this known/expected behaviour?

**Comment by Lexx2k** [comment]
Music was never in a .dat file and the .cfg paths are all pointing to folders, so I'm blindly assuming the game simply doesn't look for the tracks in the .dat file.

**Comment by burner1024** [comment]
/lst themselves are shit, I wonder if they could be dropped altogether, but that's another topic.../

**Comment by NovaRain** [comment]
Override the paths from `music_path1` and `music_path2` in fallout2.cfg.
I'm not sure what it originally tried to fix in ten years ago. Maybe it's related to why old GOG (and inherited in later digital release) put music .acm files in `<GameRoot>\sound\music\` instead of `<GameRoot>\Data\sound\music\` (original CD release).
```
sfall 2.12
>Added a fix for the original engine issue that could cause fallout to look for the music in the wrong folder
```

**Comment by burner1024** [comment]
So if it's basically a fix, then it could enabled by default and dropped?

What about music in dat?

**Comment by NovaRain** [comment]
> 
> 
> So if it's basically a fix, then it could enabled by default and dropped?
> 

Without the "fix", if `music_path1/2` are not set or missing from fallout2.cfg for some reason, the engine will write the default paths using "sound\music\\" string. And for original installation from CD this would cause the game not to have any music because CD installer copied music to "data\sound\music\\". OverrideMusicDir=1 changes the default path string to "data\sound\music\\" for game initialization, not sure about =2 though.

If we want to remove (force enable) it, I think it's better to change the default path string for only one setting (music_path1), so the engine would use both paths, like how killap made RP installer to edit fallout2.cfg.

**Comment by burner1024** [comment]
Cool, so what about music in dats? Is it supposed to work? If not, would it be too hard to make it?

**Comment by FakelsHub** [comment]
Вряд ли там есть хоть какой-то намек, на поддержку чтения из дат.
Хотело бы сделать, чтобы музыка читалась не только из этих двух папок, но и из папок расположенных в папках MODS\ например, но музыка это наименьшее, чем бы хотелось сейчас заниматься.

**Comment by burner1024** [comment]
Ну и ладно.
Хотя бы с опцией разберитесь тогда, а то неясно, что она делает, и в описании ерунда какая-то.

**Comment by FakelsHub** [comment]
Все там понятно с опцией
если в конфиге не установлены пути то sfall установит по дефолту путь к папкам `data/sound/music`
Значение 2, всегда будет переопределять путь к `data/sound/music`

**Comment by NovaRain** [comment]
With OverrideMusicDir=2 and `music_path1/2=sound\music\` in cfg, the game still doesn't play music in `data\sound\music\`.

**Comment by FakelsHub** [comment]
Why is it still open, is there some problem with that?

**Comment by NovaRain** [comment]
> 
> 
> Why is it still open, is there some problem with that?

Nah, I just forgot.
