### ISSUE TITLE
obj_can_see_obj script function

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#298]
The function cannot see any object or critter that is located behind another critter.
So the question is is this normal behavior?

**Comment by NovaRain** [comment]
I think it is, since it's "see" and obviously people don't have x-ray vision.

**Comment by Lexx2k** [comment]
I agree, but also have to say that sometimes this sucks pretty hard. In et tu encounters for example it often happens that critters won't attack you, because party members are standing around the player and thus hostile critters don't "see" the player.

**Comment by NovaRain** [comment]
You can try using WITHINPERCEPTION hook to force the detection for certain enemies.

**Comment by Lexx2k** [comment]
I know that we can workaround this, but it sucks nonetheless. :p

**Comment by FakelsHub** [comment]
> I think it is, since it's "see" and obviously people don't have x-ray vision, not even in Fallout world.

, you see another person behind another in everyday life, don't you?)))

**Comment by FakelsHub** [comment]
make_straight_path_func

> You can try using WITHINPERCEPTION hook to force the detection for certain enemies.

This doesn't seem to help because the make_straight_path_func function will return the first object in the view path that isn't equal to the specified target.

**Comment by NovaRain** [comment]
> 
> 
> > I think it is, since it's "see" and obviously people don't have x-ray vision, not even in Fallout world.
> 
> Well, you see another person behind another in everyday life, don't you?)))

Sure, but it's a game not a simulator, so I'm perfectly fine with the game doing simpler blocking check. If you want a "realistic" function for seeing, IMO the better way for cases like this is to make another script function with _extra ability_ instead of altering the the behavior of original function, like how `critter_inven_obj2` is to critter_inven_obj, unless it's really causing issues in the game like the old `wield_obj_critter` broke player's armor stats during New Reno boxing.

**Comment by FakelsHub** [comment]
How about using an existing fix for the function in the ObjSeeObj_ShootThruFix option?
Instead of adding a new function.

**Comment by FakelsHub** [comment]
Additionally, the function can't see objects like items and containers, while walls and scenery can be set as targets.

**Comment by NovaRain** [comment]
> 
> 
> How about using an existing fix for the function in the ObjSeeObj_ShootThruFix option?
> Instead of adding a new function.

No, honestly I hate that _fix_ option, because it brings more trouble (modder has to edit tons of blockers in maps to prevent the unexpected case like New Reno secret transaction, unless he makes new maps with the idea in mind) than the stuff it's supposed to _make realistic_.

I still think it's better to create `obj_can_see_obj2` if you want an extended seeing function.

**Comment by Lexx2k** [comment]
Personally I wouldn't mind some form of `obj_can_see_obj_advanced` additionally, so we keep the vanilla function the way it works.

Thing is, I'm not sure if changing `obj_can_see_obj` would break anything in the vanilla game, so I'd rather not touch it at all. NovaRain is right with the `ObjSeeObj_ShootThruFix` option .. it's really bad and just causes more issues.

**Comment by FakelsHub** [comment]
> in maps to prevent the unexpected case like New Reno secret transaction, unless he makes new maps with the idea in mind) t

So it should make new cards with this idea in mind by default, and not as in all modifications with incorrectly installed blockers.

**Comment by NovaRain** [comment]
> So it should make new cards with this idea in mind by default, and not as in all modifications with incorrectly sets blockers.

Cards? Anyway, my opinion still stands, a new function is better because a modder can use it in smaller mods for vanilla game/older TCs without the need to modify existing maps for enabling the _fix_ option just wanting new behaviors.

**Comment by FakelsHub** [comment]
obj_can_see_obj_advanced - it will also include a fix for the Shoot flag, otherwise I don't see the point of doing another bad function.

**Comment by NovaRain** [comment]
> 
> 
> obj_can_see_obj_advanced - it will also include a fix for the Shoot flag, otherwise I don't see the point of doing another bad function.

That's fine. The new function can be used on all kinds of objects like items/contianers, and have other extended behaviors like the watcher able to see through critters or objects with ShootThru flag, etc. Actually I think the old option could be removed if we implement the new function, so if one wants watcher able to see though objects with ShootThru flag, he can just use the new obj_can_see_obj_adv instead of vanilla obj_can_see_obj.

**Comment by Lexx2k** [comment]
Agreed. The ddraw option just causes bugs in unforseen places, so I'd say removing it is a good idea.

**Comment by NovaRain** [comment]
Given that there's no actual need for the new function, and `ObjCanSeeObj_ShootThru_Fix` option has received some decent updates in recent releases to make it work in a more realistic way, I'll close this issue for now until someone really needs the new `obj_can_see_obj_ext` or similar function.

**Comment by FakelsHub** [comment]
_strangely, you close something that is still active, and what you need to close is still open for a long time)_

**Comment by NovaRain** [comment]
> 
> 
> _strangely, you close something that is still active, and what you need to close is still open for a long time)_

Care to elaborate?
