### ISSUE TITLE
Show more letters in a long name

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#305]
Is it possible to use the rest of the empty space in Character Editor to show more letters in case of a long player name?

**Comment by NovaRain** [comment]
Not sure what you mean, something like this?
![Imgur](https://i.imgur.com/NCMN6Ll.png)

**Comment by blackpaulillyria** [comment]
Yes, that's it! :D
I would probably just center the name instead of keeping it aligned to the left if it's possible to keep it in line with other labels next to it

**Comment by NovaRain** [comment]
By default the maximum text width of the player name in the character screen is 100px. Because the limit value takes 1 byte, increasing it to a max of 127 (signed char) should be good enough (example with 126px width):
![Imgur](https://i.imgur.com/pbKXpEY.png)
`SafeWriteBatch<BYTE>(127, {0x435160, 0x435189});`

**Comment by blackpaulillyria** [comment]
That's perfect! 
Thank you, sir :)
