### ISSUE TITLE
Fix for shoot_along_path (burst attack)

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#317]
Interested in your opinion.

original code
```
hits = 0;
// if one or first bullet does not hit, then all the others bullets go to the next target
while ( roll_random_(1, 100) <= hitChance && _bullets > 0 )
{
   --_bullets;                     
   ++hits; // bullet hit, check the next one
}
```
replace to fix
```
bull = _bullets
while ( _bullets > 0 ) // check every bullet on current target
{
   if (roll_random_(1, 100) <= hitChance) ++hits;
   --_bullets;                      
}
_bullets = bull - hits  // the remaining bullets go to the next target
```

The disadvantage is that this approach will increase force burst attack.

**Comment by NovaRain** [comment]
> The disadvantage is that this approach will increase force burst attack.

Not sure what the "increase force burst attack" means. It seems to me more like a tweak instead of a fix.
For a group of 10 bullets from a burst, in original it _might_ roll ten times, with the fix it will always roll ten times? What's the difference in result if the 5th roll fails? Shouldn't both be to check the total damage from 5 hits?

**Comment by FakelsHub** [comment]
Another option fixes for spray mod
```
bull = _bullets
while ( _bullets > 0 )
{
   if (roll_random_(1, 100) <= hitChance) 
       ++hits;
       --_bullets;       
   else
       _bullets /= 2 // for miss where: 2 div modificator in ddraw.ini
}
_bullets = bull - hits
```

**Comment by NovaRain** [comment]
It looks kinda unnecessary IMO.

**Comment by FakelsHub** [comment]
Player ----------> T1   T2   x|
burst: 10 bullets
1. Target T1 checks all 10 bullets, 4 of them hit, 6 go to the target T2 
2. Target T2 is checked by 6 bullets, 3 of them hit, 3 go to X (nowhere)

**Comment by NovaRain** [comment]
It seems to me you want to change "one missed = the rest are missed" to "one missed = still check the rest".
If target T1 is hit with 4 bullets, in the original it means the 5th roll fails (skip the rest), with the fix it means 6 rolls fail.
Looks like it would make T1 have higher chance receiving higher damage because now it's harder for other bullets hitting T2.

**Comment by FakelsHub** [comment]
Yes, the bullets will be more likely to hit, and therefore cause more damage to first target in the line of fire. 
In the original, the third target can take significant damage, while the first and second are likely to not get damaged (often noticed, first receives nothing, the second dies).

In General, I understand you.
