### ISSUE TITLE
PlayIdleAnimOnReload doesn't work

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#320]
I can't get PlayIdleAnimOnReload to work. I presume it means the player plays the reloading weapon animation when this is set to 1 and he is reloading the weapon. Correct me if I'm wrong

**Comment by NovaRain** [comment]
Yep, it seems broken since 4.2.3.

**Comment by FakelsHub** [comment]
If read the option name this is: 
Play the Idle animation when reloading a weapon? - what nonsense!.
I think the option can be deleted as unused.

**Comment by NovaRain** [comment]
> 
> 
> If read the option name this is:
> Play the Idle animation when reloading a weapon? - what nonsense!
> I think the option can be deleted as unused.

Well, because for many weapons their "idle animation" also looks like the dude reloads the weapon. I suppose the refactoring to `intface_item_reload_hook()` in MiscPatches broke it.

**Comment by FakelsHub** [comment]
The essence of the option: play the IDLE animation when reloading weapons.
What does idle animation have to do with it?
In General, I do not understand why this is necessary.

**Comment by NovaRain** [comment]
> 
> 
> The essence of the option: play the IDLE animation when reloading weapons.
> What does idle animation have to do with it?
> In General, I do not understand why this is necessary.

It's a fairly old option existed since 1.43b before I started participating sfall development.
My guess is some people wanted to see the player do something when reloading weapons, but obviously it's not practical to require/add new animation FRMs just for that. It so happened that some weapons' idle animation _look like_ the player is reloading the gun (especially SMG & rifle) and idle animation is always available. Personally I never use the option, but some people might still like/use it, and it's been working before 4.2.3 so I think we should fix it instead of removing it.
