### ISSUE TITLE
PipboyTimeAnimDelay working wonky with certain HRP settings

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#44]
When PipboyTimeAnimDelay is set to 0:
- On vanilla fallout, sleeping is instant.
- With RP, too - if you use "basic" or "directdraw 7" graphics modes.
- If swicthed to "DirectX 9", sleeping is faster but not instant anymore. That's on 640x480x8. If you start to increase resolution and/or color depth, sleeping slows down further. On 1280x800x32, no speedup is noticeable.

**Comment by NovaRain** [comment]
Does the slowing down in HRP DX9 mode still happen with the default value (50)? If yes, then it has nothing to do the setting itself.

**Comment by burner1024** [comment]
Nothing slows down, except sleeping itself. Essentially, the effect of the setting gradually dissipates as resolution/color depth go up.

**Comment by NovaRain** [comment]
Looks like the problem is how HRP renders Pipboy UI animations in its DX9 mode, not something sfall can do without intervening in HRP. I don't have the knowledge for those DirectX stuff, and Mash doesn't release the source code yet. I'd suggest using DirectDraw compatibility tool with DD7 mode for now if you really need instant sleeping.

**Comment by burner1024** [comment]
I'm fine (well, more or less) with sleeping speed. Just thought I'd report that, anyway.

**Comment by phobos2077** [comment]
I think there's a dedicated place in hell for people who make awesome software that needs updating then vanish without releasing the source code.
