### ISSUE TITLE
Disabling Horrigan encounter

### ISSUE THREAD

**Issue by maryo** [phobos2077/sfall#50]
@NovaRain
Hi. I am trying to upgrade Fallout 1.5: Resurrection's sfall using the stripped loader and it seems like the 
`DisableHorrigan=1` option does not work.
I've met a black screen encounter ater travelling some some time so I had to enable that option in the loader again (BTW I've re-enabled also Hi-Resolution Patch and the DAT extraction). Otherwise it seems working well so far.
Thanks again!

**Comment by NovaRain** [comment]
At what date in the game you got the supposed Horrigan encounter?

**Comment by maryo** [comment]
Actually no. I'm sorry. It is not caused by sfall. It was caused by commented `/* Disable other reps */...`
I forgot I uncommented also this one before reporting this issue :-/

**Comment by maryo** [comment]
@NovaRain
Wel... :)... FYI... Looks like I was wrong again, I have mess in my builds (switching several exes). It was realy the Horrigan encounter but when I wanted to check the date I noticed even PIP BOY is not installed so I realized it's a different problem. I was testing this issue using my saved games (they seem to load properly at first sight) so it is probably connected to that - PIP BOY is installed when I start a new game. It is actually not a problem since we don't plan it to be compatible, just needs some more testing. You wrote some time before the saved games were working for you so I'm wodering how is that possible. Sound strange that you didn't notice. Or did you just check whether it loads and the you payed a new game?

**Comment by NovaRain** [comment]
Yes I only check if my party members lost their bonus stats, and because you said the new release won't be compatible to old saves, I didn't spend much time on verifying my old saves.

Judging from the code of fores loader, it's because sfall and the loader use different approaches: sfall is setting both related internal variables to 1, and the loader is always skipping related checks but never sets the variables. So in old saves they never record "player got the vault suit" and "player met Horrigan". Another good reason to use sfall built-in features instead of the loader I guess.
