### ISSUE TITLE
Naming scheme for engine-related stuff

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#56]
Need to decide on following topics. 

1. How to name our Fallout Engine structs? In existing code there was no majority in naming, but most prominent is "sTile", "sMap", etc. I'm not sure it's a good scheme though.

2. How to name our namespaces for engine variables, wrappers and structs. Need something consistent. Current version is not final.

**PS:** because we extracted real original names for all engine functions and many variables, we will use the same names for function wrappers and variable pointers.

**Comment by phobos2077** [comment]
My thoughts. I want to see Sfall (C/C++ part) working with engine stuff like we have actual source code. In this regard, it might be better to put all function wrappers, variable pointers and structs into a single namespace, because in original source there was no namespaces (C doesn't have them). 

Wrappers will have exactly the same signature as functions they call. But it's impossible to do the same for variables, because we still need to dereference them by pointer, while in original source they were accessed directly. One possible solution is to declare wrappers for variables as well - they will return variable references instead of pointers, so you don't need additional * symbol to access it.

Raw offsets (used in ASM code) will remain in different namespaces.

**Comment by phobos2077** [comment]
Ok it seems it is possible to use variable references instead of pointers. That's good news. References are definitely [the tool for the job](http://stackoverflow.com/questions/728233/why-are-references-not-reseatable-in-c) to work with FO variables.

**Comment by Vennor** [comment]
Hi! My experience with sfall is brief, but I took a look at the refactored code. Here's some thoughts.

1. Unless there's a good reason not to, migrate to MSVC 14. This way sfall can leverage C++11 and a part of C++14.
2. Use `enum class` to get rid of enumeration key prefixes.
3. I'd go with simple, clear and descriptive names for structs, eg. `InventoryRecord` is `TInvenRec`, `GameObject` is `TGameObj`. But if these are original engine names, changing them would mean that the same is possible for variables, functions etc. and as their naming is far from neat and tidy, they could use refactoring too. That'd mean changing pretty much all of the names in sfall code base.
4. `DWORD` seems to be defined in multiple places. Why not define it in a dedicated header file like types.h? Another thing you can do is using IntSafe.h. Still, I'd suggest using `std::uint32_t` from cstdint instead.
5. One way of improving the `_WRAP_WATCOM_CALLn` or `_VAR_` macros is using parameter number "overloading". [More here](https://stackoverflow.com/questions/11761703/overloading-macro-on-number-of-arguments).
6. Why is `ArrayWrapper` type needed in Variables.h? You can use multidimensional array references all right. Is it possible to store variable addresses in constants instead of using preprocessor's defines? If not, I'd move the defines to a dedicated file and only include it where it's a must. Also, I'd drop all the macros and use raw code for the sake of clarity. It's not like to code will change a lot and the macros make it way less readable.
7. When it comes to namespaces, I'd go with something like this. Use two main namespaces: `sfall` and `fallout`. The former should contain all of the extensions sfall provides, ie. the new code. While the latter should contain all that links sfall to Fallout, ie. wrappers, adapters, pointers, references. I'd also divide the fallout namespaces into dedicated groups: `enumeration`, `structure`, `variable` and `function`. `fallout::function` is where I see all the wrappers placed. In order to "hide" the raw offsets I'd place them in a nested `fallout::function::address` namespace. If you decide to store variable addresses in constants, then fallout::variable::address seems like a proper place for them. You can adjust the names of course.

**Comment by phobos2077** [comment]
Hi, Vennor! Thanks for your input. Surprisingly our thoughts are very similar on most points.

> One way of improving the _WRAP_WATCOM_CALLx or _VARx_ macros is using parameter number "overloading"

I think that will not work because I need to push each corresponding argument to specific register or stack. __VA_ARGS__ won't help here.

> Why is ArrayWrapper type needed in Variables.h? You can use multidimensional array references all right. Is it possible to store variable addresses in constants instead of using preprocessor's defines?

I've spent an entire day trying to figure out how to instruct compiler to make a reference to multidimensional array with pre-defined address. Nothing worked, so I just created this simple struct. From the code perspective it should 99% mimic the multidimensional array functionality. So if anyone finds how to implement it with simple arrays, no need to change code.

> Use enum class to get rid of enumeration key prefixes.
I agree, but some defines are taken from FO script sources (DEFINE.H, etc.) and they had these prefixes. For other reverse-engineered enums we can use enum class. But that will require migrating to latest visual studio.

I mostly agree about namespaces. But I was thinking about something shorter. We have a LOT of ASM code (and it gets bigger all the time, as we integrate more and more Crafty's changes), so something like FO::FuncOffs probably? 

> I'd also divide the fallout namespaces into dedicated groups: enumeration, structure, variable and function

Wouldn't it be too verbose? I was thinking to place all stuff that looks like non-existing FO source code in one namespace for simplicity :)

PS: Is it common to use lowercase for namespaces in C++ projects? I mean for actual user code, not libraries.

**Comment by Vennor** [comment]
> I think that will not work because I need to push each corresponding argument to specific register or stack. VA_ARGS won't help here.

It should work fine since you retain separate macros for different number of parameters, but add a single helper macro that uses them internally.

>I've spent an entire day trying to figure out how to instruct compiler to make a reference to multidimensional array with pre-defined address. Nothing worked, so I just created this simple struct. From the code perspective it should 99% mimic the multidimensional array functionality. So if anyone finds how to implement it with simple arrays, no need to change code.

Try this: `type (&name)[N][M] = *reinterpret_cast<type(*)[N][M]>(address)`. Or better, if the compiler allows you, `auto name  = *reinterpret_cast<type(*)[N][M]>(address)`.

> I agree, but some defines are taken from FO script sources (DEFINE.H, etc.) and they had these prefixes. For other reverse-engineered enums we can use enum class. But that will require migrating to latest visual studio.

Oh. I guess it's all or nothing then. Either use original naming or refactor all the names.

> I mostly agree about namespaces. But I was thinking about something shorter. We have a LOT of ASM code (and it gets bigger all the time, as we integrate more and more Crafty's changes), so something like FO::FuncOffs probably?

I think you could use something like `fo::e` instead of `fallout::enumeration`, but I'm not sure if it's clear enough.

> Wouldn't it be too verbose? I was thinking to place all stuff that looks like non-existing FO source code in one namespace for simplicity :)

Depends on your preferences. I often use more than one namespace in my code to separate responsibilities. I suggested separate namespaces to avoid pollution since there's a lot of types stuffed into just a couple headers.

> PS: Is it common to use lowercase for namespaces in C++ projects? I mean for actual user code, not libraries.

I cannot say if it's common, but I've never seen otherwise. Let alone sfall. :)

**Comment by phobos2077** [comment]
> Try this: type (&name)[N][M] = *reinterpret_cast<type(*)[N][M]>(address).

Tried it, didn't work even under VS2015. `Error: C2101: '&' on constant.`
I also tried declaring additional variable holding simple pointer, so it can compile, but it didn't dereference pointer properly. It seemed to always point to the variable I declared, not the FO engine variable itself.

> I cannot say if it's common, but I've never seen otherwise. Let alone sfall. :)

Well, there is [Falltergeist ](https://github.com/falltergeist/falltergeist/blob/master/src/Game/Game.h) for one :)

**Comment by Vennor** [comment]
> Tried it, didn't work even under VS2015. Error: C2101: '&' on constant.
I also tried declaring additional variable holding simple pointer, so it can compile, but it didn't dereference pointer properly. It seemed to always point to the variable I declared, not the FO engine variable itself.

Indeed it doesn't compile if you pass a number literal as the `reinterpret_cast` argument and specify the type explicitly, but it does if you store the address in a variable and pass it as the argument or declare the reference as `auto`. I'm not sure as to why it only works like this yet, but will investigate it.

```cpp
const auto address = 0x510944;
type (&name)[N][M] = *reinterpret_cast<type(*)[N][M]>(address);
```
```cpp
auto name = *reinterpret_cast<type(*)[N][M]>(0x510944);
```

**Comment by phobos2077** [comment]
> const auto address = 0x510944;
> type (&name)[N][M] = *reinterpret_cast<type(*)[N][M]>(address);

This is what I actually tried - the compiler will store the address of "address" variable as a target for reference, instead of the actual engine varaible. Tried casting to "pointer-to-pointer" and dereferencing twice - didn't work either. It seems to me there is a mess in compiler regarding static arrays. Also it's not convenient to declare them, that's why I've added a struct.

**Comment by Vennor** [comment]
> This is what I actually tried - the compiler will store the address of "address" variable as a target for reference, instead of the actual engine varaible. Tried casting to "pointer-to-pointer" and dereferencing twice - didn't work either. It seems to me there is a mess in compiler regarding static arrays. Also it's not convenient to declare them, that's why I've added a struct.

Maybe I'm not recreating the same environment, but it works fine in [my little test application](https://ideone.com/XiVZvb).

**Comment by phobos2077** [comment]
I don't know, but in VS 2015 such setup does not work for some reason. Reference variable only points to a bunch of memory where _address_ variable starts, not where it pointed originally. Maybe compiler can't handler such unusual use case.

`
int src[1][2] = {{2, 5}};
int address = reinterpret_cast<int>(&src);
int (&wtf)[1][2] = *reinterpret_cast<int(*)[1][2]>(address);
`

**Comment by Vennor** [comment]
Well, I just pasted your code into an empty project and it works flawlessly for me on VS 2015. It might be a problem with your setup, but I cannot see how is it possible that the second array variable references the address variable which is of a different type.

Have you tried the `auto` approach?

**Comment by phobos2077** [comment]
How do you know that it works? I place breakpoint and inspect the values. Also I try to change value using the reference variable. Doesn't work properly. I upgraded my project to VS 2015 toolset, but no luck :(

**Comment by Vennor** [comment]
Take a look at the code I linked above. I read and write through the reference. When testing your code I also compared addresses of the array and its reference - they match perfectly.

**Comment by phobos2077** [comment]
The final naming scheme:
`sfall::` for all sfall code, except related to the engine;
`fo::` for all engine-related code (all types - structs and enums, placed directly in this namespace);
`fo::func::` function wrappers ("bridges" to engine functions that you can call like normal C/C++ functions);
`fo::funcoffs::` engine function offset constants (specifically for use inside asm blocks);
`fo::var::` for engine variable references.

Engine variable offsets had to be left as `#define` constants. This is because how Visual C++ inline assembler works. You can't just use normal constants when working with memory addresses... 
For those, `FO_VAR_` prefix is used.
