### ISSUE TITLE
Have you considerer using lua for the scripts?

### ISSUE THREAD

**Issue by salvadorc17** [phobos2077/sfall#64]
Just have seen this and seems interesting, do you think using lua will help creation of scripts for the game using this library?

**Comment by phobos2077** [comment]
Yes we already considered Lua scripting and though it is way better than SSL and I'm a fan of Lua myself, integrating it just doesn't seem to be interesting to modders. 99% of modders doesn't know SSL very well and programming in general and will unlikely be using Lua for scripting.

**Comment by salvadorc17** [comment]
Still i think can be more user friendly for modders lua than other, maybe thats the reason why people dont like scripting in this game, is the project halted or still have todo?

**Comment by phobos2077** [comment]
Just browse the current issues, it contains all current plans for development. The project is not actively developed because there is only like 3 contributors. There's also another version of Sfall with slightly more features, but it's not on github and different codebase makes it hard to integrate features properly.
