### ISSUE TITLE
The exploit in hs_invenwield

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#68]
Here's a sample of hs_invenwield.ssl:
```
procedure start;

procedure start begin
  if not init_hook then begin
    variable critter := get_sfall_arg, item := get_sfall_arg, slot := get_sfall_arg, hooktype := get_sfall_arg;
    if (slot == 0) and (party_member_obj(obj_pid(critter)) != 0) then begin
      if (hooktype == 1) then begin
        set_critter_extra_stat(critter, 8, get_critter_extra_stat(critter, 8)+2);
      end else begin
        set_critter_extra_stat(critter, 8, get_critter_extra_stat(critter, 8)-2);
      end
      display_msg(hooktype+", "+obj_name(item)+", "+get_critter_extra_stat(critter, 8));
    end
  end
end
```
Give a leather jacket to Sulik (or anyone) and wield on him with "Use Best Armor" button, then without telling him to remove, give him a leather armor and wield again - you will see him receiving an unplanned AP +2 bonus. Looks like hs_invenwield doesn't take "NPCs replacing their current equipped items" as "unwield than wield" two actions, only one "wield" action.

**Comment by phobos2077** [comment]
I think there is a work around available. When hooktype == 1 add a check for any existing item on the critter. If item was "unwielded" before then the hooktype = 0 hook will get executed. Otherwise the item should still exist (because hook script is called BEFORE the engine handler) and you can rely on that to remove any previously added "effects".

I can think of more reliable solution for tracking all scripted effects on critters using saved arrays, etc.

All in all, I think this is not a bug and shouldn't be fixed by sfall. Right now this hook does exactly what it's supposed to - hooks to every single call to 2 engine functions: invenWieldFunc() and invenUnwieldFunc().

**Comment by NovaRain** [comment]
You're right. Adding some checks does prevent the "exploit". In case anyone is interested in, here's the fixed one:
```
procedure start;

procedure start begin
  if not init_hook then begin
    variable critter := get_sfall_arg, item := get_sfall_arg, slot := get_sfall_arg, hooktype := get_sfall_arg;

    if ((slot == 0) and (party_member_obj(obj_pid(critter)) != 0)) then begin
      if ((hooktype == 1) and obj_pid(critter_inven_obj(critter, slot)) <= 0) then begin
        set_critter_extra_stat(critter, STAT_max_move_points, get_critter_extra_stat(critter, STAT_max_move_points)+2);
      end else if (hooktype == 0) then begin
        set_critter_extra_stat(critter, STAT_max_move_points, get_critter_extra_stat(critter, STAT_max_move_points)-2);
      end
      display_msg(hooktype + ", " + obj_name(item) + ", " + get_critter_extra_stat(critter, STAT_max_move_points));
    end
  end
end
```
