### ISSUE TITLE
Move CombatControl to script

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#87]
Need to move PartyControl mod into hook-based script.

**Comment by FakelsHub** [comment]
It seems that you need to block the party members from leaving the map when they are under player control?

**Comment by NovaRain** [comment]
> 
> 
> It seems that need to blocking leaving the map for the party members when they are under player control?

Why? Is there something wrong with that?

**Comment by Lexx2k** [comment]
I actually like that I can leave the map with party members. :>

**Comment by FakelsHub** [comment]
That's just against such actions, when an unnecessary npc is at the exit from the map,the whole group is in battle, and at a critical moment for the group, npc leaves the map.  And then the cured come back and finish their work.
 In general, make the same as in all tactical games.

**Comment by Lexx2k** [comment]
You would have to block the map exit for all party controlled critters then - and only trigger the exit if everyone is in the grid. Otherwise I can just abuse the mechanic with placing the actual dude_obj near the exit grid and fight with the companions and the whole mechanic is circumvented. 

But this creates a new problem:
You need to know when every party controlled critter is on the exit grid. Unlike FOnline, the exit grids in Fo are just single hex, so you actually never really know if a critter is really somewhere on the grid now or not.

For the first time I feel like this is a rabbit hole we should not go down. It doesn't really make combat better... it just causes problems that are hard to solve. :p

**Comment by FakelsHub** [comment]
> Otherwise I can just abuse the mechanic with placing the actual dude_obj near the exit grid and fight with the companions to circumvent the whole mechanic.

This is the same mechanics that exists with uncontrolled NPCs, so I want to keep the same mechanics, but if your controlled NPCs in the party have already attacked someone.

**Comment by Lexx2k** [comment]
The last few days I was playing more with combat control activated, and now I agree that map_exit should be disabled when playing as party members. It might feel a bit abstract, but most party members have so many AP and a high sequence that you can often run into the exit grid in 1 or 2 turns. It makes avoiding encounters very trivial.
