### ISSUE TITLE
Allow skill use when using set_dude_obj()

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#97]
Would it be possible to allow the use of skills (for example stealing and sneak) for critters that are under player control via set_dude_obj(x) ? I am toying around with an idea related to that, but all I get is "I can't do that" in the message log (which makes sense, considering the feature was only(?) intended for combat use).

Also, are perks synced too / can controlled critters potentially have perks? I'm thinking about stuff silent running and light step here.

**Comment by phobos2077** [comment]
I'm not sure about the perks, but I remember that skill usage was specifically disallowed when controlling other critters to prevent some issues. Not sure what those issues were though.. Maybe need to reconsider.

**Comment by FakelsHub** [comment]
`sfall_func0("real_dude_obj")`
What this  function does?

**Comment by NovaRain** [comment]
It should set the player pointer to real dude_obj.

**Comment by FakelsHub** [comment]
Skills work except sneak, this is turned off intentionally.
It is advisable to use the function only in combat mode, otherwise going to another card controlled by the critter will cause the game to surprise you, if you do not take care of switching to the player.

> Also, are perks synced too / can controlled critters potentially have perks?

No. You can do this via a script.

The issue can be closed.
